# Tests / Code Coverage workflow
# This workflow is triggered by ci_release.yml workflow
name: Tests
on:
  workflow_call:
    inputs:
      GO_VERSION:
        description: 'Go version to use'
        type: string
        required: true

jobs:
  integration_test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.GO_VERSION }}
      - name: Integration Tests
        run: cd op-e2e && make test
